baseURL = "https://www.osms.io"
languageCode = "en-us"
title = "www.osms.io"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[params]
  description     = "The last theme you'll ever need. Maybe."
  disqusShortname = "s2kproject"
  commentoEnable  = false
  title = "www.osms.io"
  favicon         = ""
  facebook        = ""
  twitter         = "https://twitter.com/shdobxr"
  instagram       = ""
  youtube         = ""
  github          = "https://github.com/shdobxr"
  gitlab          = ""
#  linkedin        = "https://www.linkedin.com/in/dan-girard/"
  mastodon        = ""
  slack           = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-red"
  featured_image = "/images/bg.png"
  #recent_posts_number = 5
