baseURL = ""
languageCode = "en-us"
title = "opensourcemotorsports"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
#Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[params]
  commentoEnable  = true
  disqusShortname = "s2kproject"
  favicon         = ""
  description     = "The last theme you'll ever need. Maybe."
  facebook        = ""
  twitter         = "https://twitter.com/shdobxr"
  instagram       = ""
  youtube         = ""
  github          = ""
  gitlab          = ""
  linkedin        = ""
  mastodon        = ""
  slack           = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-red"
  featured_image = "/images/bg.png"
  recent_posts_number = 2
